#!/usr/bin/python3
def raise_exception():
    proposition = [1, 'think']
    resultat = proposition[0] + proposition[1]
    return resultat
