>>> BaseGeometry = __import__('7-base_geometry').BaseGeometry

>>> bg = BaseGeometry()

>>> bg.integer_validator("my_int", 12)

>>> bg.integer_validator("width", 89)

>>> bg.area()
Traceback (most recent call last):
Exception: area() is not implemented

>>> bg.integer_validator("letter", "a")
Traceback (most recent call last):
TypeError: letter must be an integer

>>> bg.integer_validator("name", "John")
Traceback (most recent call last):
TypeError: name must be an integer


>>> bg.integer_validator("integer", 0)
Traceback (most recent call last):
ValueError: integer must be greater than 0

>>> bg.integer_validator("negatif", -10)
Traceback (most recent call last):
ValueError: negatif must be greater than 0



>>> bg = BaseGeometry(5)
Traceback (most recent call last):
...
TypeError: BaseGeometry() takes no arguments

>>> bg.area()
Traceback (most recent call last):
...
Exception: area() is not implemented


>>> bg.area(5)
Traceback (most recent call last):
...
TypeError: area() takes 1 positional argument but 2 were given


>>> bg.integer_validator()
Traceback (most recent call last):
...
TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'


>>> bg.integer_validator("Hello")
Traceback (most recent call last):
...
TypeError: integer_validator() missing 1 required positional argument: 'value'


>>> bg.integer_validator("Hello", 2, 2)
Traceback (most recent call last):
...
TypeError: integer_validator() takes 3 positional arguments but 4 were given


>>> bg.integer_validator("Test", 2)


>>> bg.integer_validator("Test", -2)
Traceback (most recent call last):
...
ValueError: Test must be greater than 0


>>> bg.integer_validator("Test", 0)
Traceback (most recent call last):
...
ValueError: Test must be greater than 0


>>> bg.integer_validator("Test", 1.0)
Traceback (most recent call last):
...
TypeError: Test must be an integer


>>> bg.integer_validator("Test", -1.0)
Traceback (most recent call last):
...
TypeError: Test must be an integer


>>> bg.integer_validator("Test", True)
Traceback (most recent call last):
...
TypeError: Test must be an integer


>>> bg.integer_validator("Test", [1])
Traceback (most recent call last):
...
TypeError: Test must be an integer


>>> bg.integer_validator("Test", (1, ))
Traceback (most recent call last):
...
TypeError: Test must be an integer


>>> bg.integer_validator("Test", {1})
Traceback (most recent call last):
...
TypeError: Test must be an integer


>>> bg.integer_validator("Test", {1: 1})
Traceback (most recent call last):
...
TypeError: Test must be an integer


>>> bg.integer_validator("Test", None)
Traceback (most recent call last):
...
TypeError: Test must be an integer


>>> bg.integer_validator("Test", "1")
Traceback (most recent call last):
...
TypeError: Test must be an integer